[2023-12-07 22:14:44,548] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.cargar_data manual__2023-12-07T21:54:18.648009+00:00 [queued]>
[2023-12-07 22:14:44,561] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.cargar_data manual__2023-12-07T21:54:18.648009+00:00 [queued]>
[2023-12-07 22:14:44,562] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 22:14:44,563] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-12-07 22:14:44,563] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 22:14:44,581] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cargar_data> on 2023-12-07 21:54:18.648009+00:00
[2023-12-07 22:14:44,588] {standard_task_runner.py:52} INFO - Started process 758 to run task
[2023-12-07 22:14:44,592] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'cargar_data', 'manual__2023-12-07T21:54:18.648009+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmp4fb3o2s4', '--error-file', '/tmp/tmp9bzb1q00']
[2023-12-07 22:14:44,593] {standard_task_runner.py:80} INFO - Job 172: Subtask cargar_data
[2023-12-07 22:14:44,665] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.cargar_data manual__2023-12-07T21:54:18.648009+00:00 [running]> on host 4357a10b93bd
[2023-12-07 22:14:44,709] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-07 22:14:44,752] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=cargar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-07T21:54:18.648009+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-07T21:54:18.648009+00:00
[2023-12-07 22:14:44,758] {logging_mixin.py:115} INFO - Cargando la data para la fecha: 2023-12-07 21
[2023-12-07 22:14:46,910] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 183, in cargar_data
    execute_values(cur, insert_sql, values)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type date: ""

[2023-12-07 22:14:46,923] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_redshift_docker_***, task_id=cargar_data, execution_date=20231207T215418, start_date=20231207T221444, end_date=20231207T221446
[2023-12-07 22:14:46,941] {standard_task_runner.py:97} ERROR - Failed to execute job 172 for task cargar_data (invalid input syntax for type date: ""
; 758)
[2023-12-07 22:14:46,973] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-07 22:14:47,005] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
