[2023-12-06 11:38:19,263] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.transformar_data scheduled__2023-12-05T00:00:00+00:00 [queued]>
[2023-12-06 11:38:19,276] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.transformar_data scheduled__2023-12-05T00:00:00+00:00 [queued]>
[2023-12-06 11:38:19,276] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-06 11:38:19,277] {taskinstance.py:1377} INFO - Starting attempt 4 of 6
[2023-12-06 11:38:19,277] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-06 11:38:19,291] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_data> on 2023-12-05 00:00:00+00:00
[2023-12-06 11:38:19,295] {standard_task_runner.py:52} INFO - Started process 917 to run task
[2023-12-06 11:38:19,298] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'transformar_data', 'scheduled__2023-12-05T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmprata2bda', '--error-file', '/tmp/tmp6i3v128s']
[2023-12-06 11:38:19,299] {standard_task_runner.py:80} INFO - Job 30: Subtask transformar_data
[2023-12-06 11:38:19,358] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.transformar_data scheduled__2023-12-05T00:00:00+00:00 [running]> on host 4357a10b93bd
[2023-12-06 11:38:19,396] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-06 11:38:19,428] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=transformar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-05T00:00:00+00:00
[2023-12-06 11:38:19,429] {logging_mixin.py:115} INFO - Transformando la data para la fecha: 2023-12-05 0
[2023-12-06 11:38:19,430] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 101, in transformar_data
    fullpage_movie = pages[f'df_movie_{1}']
KeyError: 'df_movie_1'
[2023-12-06 11:38:19,440] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_redshift_docker_***, task_id=transformar_data, execution_date=20231205T000000, start_date=20231206T113819, end_date=20231206T113819
[2023-12-06 11:38:19,455] {standard_task_runner.py:97} ERROR - Failed to execute job 30 for task transformar_data ('df_movie_1'; 917)
[2023-12-06 11:38:19,470] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-06 11:38:19,506] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
