[2023-12-06 19:16:08,629] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.extraer_data manual__2023-12-06T19:16:07.113074+00:00 [queued]>
[2023-12-06 19:16:08,640] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.extraer_data manual__2023-12-06T19:16:07.113074+00:00 [queued]>
[2023-12-06 19:16:08,640] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-06 19:16:08,640] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-06 19:16:08,641] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-06 19:16:08,658] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extraer_data> on 2023-12-06 19:16:07.113074+00:00
[2023-12-06 19:16:08,663] {standard_task_runner.py:52} INFO - Started process 1646 to run task
[2023-12-06 19:16:08,666] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'extraer_data', 'manual__2023-12-06T19:16:07.113074+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmppk9df19j', '--error-file', '/tmp/tmp_8vit31h']
[2023-12-06 19:16:08,668] {standard_task_runner.py:80} INFO - Job 68: Subtask extraer_data
[2023-12-06 19:16:08,735] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.extraer_data manual__2023-12-06T19:16:07.113074+00:00 [running]> on host 4357a10b93bd
[2023-12-06 19:16:08,787] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-06 19:16:08,824] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=extraer_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-06T19:16:07.113074+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-06T19:16:07.113074+00:00
[2023-12-06 19:16:08,825] {logging_mixin.py:115} INFO - Adquiriendo data para la fecha: 2023-12-06 19
[2023-12-06 19:16:09,444] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 82, in extraer_data
    with open(dag_path+'/raw_data/'+"data_"+str(date.year)+'-'+str(date.month)+'-'+str(date.day)+'-'+str(date.hour)+".json", "w") as json_file:
AttributeError: type object 'datetime.date' has no attribute 'hour'
[2023-12-06 19:16:09,454] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_redshift_docker_***, task_id=extraer_data, execution_date=20231206T191607, start_date=20231206T191608, end_date=20231206T191609
[2023-12-06 19:16:09,596] {standard_task_runner.py:97} ERROR - Failed to execute job 68 for task extraer_data (type object 'datetime.date' has no attribute 'hour'; 1646)
[2023-12-06 19:16:09,612] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-06 19:16:09,795] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
