[2023-12-07 22:14:31,911] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.cargar_data manual__2023-12-06T21:26:03.000440+00:00 [queued]>
[2023-12-07 22:14:31,927] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.cargar_data manual__2023-12-06T21:26:03.000440+00:00 [queued]>
[2023-12-07 22:14:31,927] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 22:14:31,928] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-12-07 22:14:31,928] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 22:14:31,948] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cargar_data> on 2023-12-06 21:26:03.000440+00:00
[2023-12-07 22:14:31,954] {standard_task_runner.py:52} INFO - Started process 746 to run task
[2023-12-07 22:14:31,956] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'cargar_data', 'manual__2023-12-06T21:26:03.000440+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmp5g2ljvde', '--error-file', '/tmp/tmpmp2swzim']
[2023-12-07 22:14:31,957] {standard_task_runner.py:80} INFO - Job 170: Subtask cargar_data
[2023-12-07 22:14:32,030] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.cargar_data manual__2023-12-06T21:26:03.000440+00:00 [running]> on host 4357a10b93bd
[2023-12-07 22:14:32,077] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-07 22:14:32,130] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=cargar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-06T21:26:03.000440+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-06T21:26:03.000440+00:00
[2023-12-07 22:14:32,131] {logging_mixin.py:115} INFO - Cargando la data para la fecha: 2023-12-06 21
[2023-12-07 22:14:35,201] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 183, in cargar_data
    execute_values(cur, insert_sql, values)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type date: ""

[2023-12-07 22:14:35,220] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_redshift_docker_***, task_id=cargar_data, execution_date=20231206T212603, start_date=20231207T221431, end_date=20231207T221435
[2023-12-07 22:14:35,240] {standard_task_runner.py:97} ERROR - Failed to execute job 170 for task cargar_data (invalid input syntax for type date: ""
; 746)
[2023-12-07 22:14:35,261] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-07 22:14:35,293] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
