[2023-12-20T20:13:56.346+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_redshift_docker_airflow.mensaje_carga_completada manual__2023-12-20T20:13:36.594339+00:00 [queued]>
[2023-12-20T20:13:56.361+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_redshift_docker_airflow.mensaje_carga_completada manual__2023-12-20T20:13:36.594339+00:00 [queued]>
[2023-12-20T20:13:56.362+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-20T20:13:56.382+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): mensaje_carga_completada> on 2023-12-20 20:13:36.594339+00:00
[2023-12-20T20:13:56.388+0000] {standard_task_runner.py:60} INFO - Started process 202 to run task
[2023-12-20T20:13:56.392+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'mensaje_carga_completada', 'manual__2023-12-20T20:13:36.594339+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmp7mea5fyh']
[2023-12-20T20:13:56.394+0000] {standard_task_runner.py:88} INFO - Job 321: Subtask mensaje_carga_completada
[2023-12-20T20:13:56.410+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-12-20T20:13:56.460+0000] {task_command.py:423} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.mensaje_carga_completada manual__2023-12-20T20:13:36.594339+00:00 [running]> on host de1b3d441485
[2023-12-20T20:13:56.691+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_redshift_docker_***' AIRFLOW_CTX_TASK_ID='mensaje_carga_completada' AIRFLOW_CTX_EXECUTION_DATE='2023-12-20T20:13:36.594339+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-20T20:13:36.594339+00:00'
[2023-12-20T20:13:58.663+0000] {logging_mixin.py:188} INFO - 'ascii' codec can't encode character '\xe1' in position 73: ordinal not in range(128)
[2023-12-20T20:13:58.678+0000] {logging_mixin.py:188} INFO - Failure
[2023-12-20T20:13:58.679+0000] {python.py:201} INFO - Done. Returned value was: None
[2023-12-20T20:13:58.693+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=ETL_redshift_docker_***, task_id=mensaje_carga_completada, execution_date=20231220T201336, start_date=20231220T201356, end_date=20231220T201358
[2023-12-20T20:13:58.737+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-20T20:13:58.764+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
