[2023-12-07 21:59:06,773] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.extraer_data manual__2023-12-06T21:18:23.839899+00:00 [queued]>
[2023-12-07 21:59:06,786] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.extraer_data manual__2023-12-06T21:18:23.839899+00:00 [queued]>
[2023-12-07 21:59:06,786] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 21:59:06,787] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2023-12-07 21:59:06,787] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 21:59:06,841] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extraer_data> on 2023-12-06 21:18:23.839899+00:00
[2023-12-07 21:59:06,848] {standard_task_runner.py:52} INFO - Started process 618 to run task
[2023-12-07 21:59:06,851] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'extraer_data', 'manual__2023-12-06T21:18:23.839899+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmpcvadxf3n', '--error-file', '/tmp/tmpknjso5el']
[2023-12-07 21:59:06,854] {standard_task_runner.py:80} INFO - Job 125: Subtask extraer_data
[2023-12-07 21:59:06,920] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.extraer_data manual__2023-12-06T21:18:23.839899+00:00 [running]> on host 4357a10b93bd
[2023-12-07 21:59:06,959] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-07 21:59:06,997] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=extraer_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-06T21:18:23.839899+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-06T21:18:23.839899+00:00
[2023-12-07 21:59:06,998] {logging_mixin.py:115} INFO - Adquiriendo data para la fecha: 2023-12-06 21
[2023-12-07 21:59:16,121] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 111, in extraer_data
    with open(dag_path + '/raw_data/' + "data_" + str(now.year) + '-' + str(now.month) + '-' + str(now.day) + '-' + str(now.hour) + ".json", "w") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/raw_data/data_2023-12-7-21.json'
[2023-12-07 21:59:16,141] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ETL_redshift_docker_***, task_id=extraer_data, execution_date=20231206T211823, start_date=20231207T215906, end_date=20231207T215916
[2023-12-07 21:59:16,164] {standard_task_runner.py:97} ERROR - Failed to execute job 125 for task extraer_data ([Errno 2] No such file or directory: '/opt/airflow/raw_data/data_2023-12-7-21.json'; 618)
[2023-12-07 21:59:16,186] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-07 21:59:16,314] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
