[2023-12-07 22:09:38,890] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.cargar_data manual__2023-12-07T21:49:05.785692+00:00 [queued]>
[2023-12-07 22:09:38,901] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.cargar_data manual__2023-12-07T21:49:05.785692+00:00 [queued]>
[2023-12-07 22:09:38,901] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 22:09:38,902] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-07 22:09:38,902] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 22:09:38,922] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cargar_data> on 2023-12-07 21:49:05.785692+00:00
[2023-12-07 22:09:38,927] {standard_task_runner.py:52} INFO - Started process 553 to run task
[2023-12-07 22:09:38,930] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'cargar_data', 'manual__2023-12-07T21:49:05.785692+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmphyye7ua9', '--error-file', '/tmp/tmpeoeb9tpp']
[2023-12-07 22:09:38,931] {standard_task_runner.py:80} INFO - Job 163: Subtask cargar_data
[2023-12-07 22:09:38,989] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.cargar_data manual__2023-12-07T21:49:05.785692+00:00 [running]> on host 4357a10b93bd
[2023-12-07 22:09:39,026] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-07 22:09:39,064] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=cargar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-07T21:49:05.785692+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-07T21:49:05.785692+00:00
[2023-12-07 22:09:39,066] {logging_mixin.py:115} INFO - Cargando la data para la fecha: 2023-12-07 21
[2023-12-07 22:09:39,066] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 155, in cargar_data
    cur = psycopg2.connect.cursor()
AttributeError: 'function' object has no attribute 'cursor'
[2023-12-07 22:09:39,077] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_redshift_docker_***, task_id=cargar_data, execution_date=20231207T214905, start_date=20231207T220938, end_date=20231207T220939
[2023-12-07 22:09:39,088] {standard_task_runner.py:97} ERROR - Failed to execute job 163 for task cargar_data ('function' object has no attribute 'cursor'; 553)
[2023-12-07 22:09:39,102] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-07 22:09:39,183] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
