[2023-12-07 22:09:28,679] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.cargar_data scheduled__2023-12-06T00:00:00+00:00 [queued]>
[2023-12-07 22:09:28,692] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.cargar_data scheduled__2023-12-06T00:00:00+00:00 [queued]>
[2023-12-07 22:09:28,693] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 22:09:28,694] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-07 22:09:28,694] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 22:09:28,721] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cargar_data> on 2023-12-06 00:00:00+00:00
[2023-12-07 22:09:28,731] {standard_task_runner.py:52} INFO - Started process 527 to run task
[2023-12-07 22:09:28,735] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'cargar_data', 'scheduled__2023-12-06T00:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmpraqzu3ip', '--error-file', '/tmp/tmpy8ka2_xt']
[2023-12-07 22:09:28,737] {standard_task_runner.py:80} INFO - Job 157: Subtask cargar_data
[2023-12-07 22:09:28,814] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.cargar_data scheduled__2023-12-06T00:00:00+00:00 [running]> on host 4357a10b93bd
[2023-12-07 22:09:28,864] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-07 22:09:28,920] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=cargar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-06T00:00:00+00:00
[2023-12-07 22:09:28,921] {logging_mixin.py:115} INFO - Cargando la data para la fecha: 2023-12-06 0
[2023-12-07 22:09:28,921] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 155, in cargar_data
    cur = psycopg2.connect.cursor()
AttributeError: 'function' object has no attribute 'cursor'
[2023-12-07 22:09:28,934] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_redshift_docker_***, task_id=cargar_data, execution_date=20231206T000000, start_date=20231207T220928, end_date=20231207T220928
[2023-12-07 22:09:28,960] {standard_task_runner.py:97} ERROR - Failed to execute job 157 for task cargar_data ('function' object has no attribute 'cursor'; 527)
[2023-12-07 22:09:28,988] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-07 22:09:29,078] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
