[2023-12-07 21:34:24,343] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.transformar_data manual__2023-12-06T19:36:56.875589+00:00 [queued]>
[2023-12-07 21:34:24,393] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.transformar_data manual__2023-12-06T19:36:56.875589+00:00 [queued]>
[2023-12-07 21:34:24,396] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 21:34:24,415] {taskinstance.py:1377} INFO - Starting attempt 4 of 6
[2023-12-07 21:34:24,421] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 21:34:24,521] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_data> on 2023-12-06 19:36:56.875589+00:00
[2023-12-07 21:34:24,567] {standard_task_runner.py:52} INFO - Started process 299 to run task
[2023-12-07 21:34:24,616] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'transformar_data', 'manual__2023-12-06T19:36:56.875589+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmpb161dyfk', '--error-file', '/tmp/tmpu5w9fg5t']
[2023-12-07 21:34:24,653] {standard_task_runner.py:80} INFO - Job 106: Subtask transformar_data
[2023-12-07 21:34:25,292] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.transformar_data manual__2023-12-06T19:36:56.875589+00:00 [running]> on host 4357a10b93bd
[2023-12-07 21:34:26,384] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-07 21:34:26,792] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=transformar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-06T19:36:56.875589+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-06T19:36:56.875589+00:00
[2023-12-07 21:34:26,831] {logging_mixin.py:115} INFO - Transformando la data para la fecha: 2023-12-06 19
[2023-12-07 21:34:26,835] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 103, in transformar_data
    fullpage_movie = pages[f'df_movie_{1}']
KeyError: 'df_movie_1'
[2023-12-07 21:34:26,908] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_redshift_docker_***, task_id=transformar_data, execution_date=20231206T193656, start_date=20231207T213424, end_date=20231207T213426
[2023-12-07 21:34:27,162] {standard_task_runner.py:97} ERROR - Failed to execute job 106 for task transformar_data ('df_movie_1'; 299)
[2023-12-07 21:34:27,206] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-07 21:34:27,636] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
